
title: BF8800
email: your-email@example.com
url: "" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
markdown: kramdown
theme: "just-the-docs"

color_scheme: "dark"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
